[gcp_service_account]
type = "service_account"
project_id = "streamlit-logger-466301"
private_key_id = "9be4d562c93d8e31309a759e7027fe94127dfb7a"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC79pqDNyngQfjy
PVoQxYQkuxyOToDmUVdMb3Ao8Eui7ylMBDuUS39MZe6JoheM+wfHWUWczm3ls1wn
JrcZNNw+qxa2dsYA++7VrDtPWIzEwbPKnWAAD5liWbhflxcXmOEyQivJAet8VCyS
8uuwLW254cTN1rvUUQZUPJd6BY5U1J+UNumyKK5o1g9LfNxnmaug3cT66ok+iWDd
8IskK2Neo+DkwasZTcdCONiW382Bm5vd4ZZMiynKfS9YRgEo1UxmI9z1dLNOKP/K
iXpTO/xBUtcwjwDOsT5EePpanwlh2My2mkjeVf570GXJmdqtwwmlaEJatEOQgMIO
KkZnNGBrAgMBAAECggEACAsfBJN1PswD77XRZ1tUcs/xAmP4nyKG9lXkelQCIJhU
b5TUyd1LNsU75nbhxB4v8Idw86tfx48b1+8Pscvxytq+b5N4mK0vRMSIizYyW+8g
FwESDR6dxTgqrCiGi/N2W5S6U/E5lwnxGF692D2xbt1q8xYH1qea+jrXjpizRQz7
cw+mw+ZMHcdRsHcnPepaysrj6afAWWY+HMbdTdUffkhscnP6ZwmxpwsZtNqjexIH
kKaBesJavnSrg/89q5TKlC8H7/KnciDZA+Z6IOmaT6/m2glt4PG/l7S0R1UvAxlb
2GZraLITDIULENwKVBEr+neUrSq4362IRo2UmNksnQKBgQDoWUnDSBCkQj7Kj7sT
+QHMVfoQeFnQDfEqzY7bVRK5ValCqhCRho6uS1i2Ygf+JOLMaQTh6ks79ChDO8/j
TiUvII3TcOugTBnRYpOL5Viqy6t6dMy7EkOsFTHfzX0umns8HUiSyZMt7zptBrBL
HHyb6bwBqWID9IgBBCrRJskW5QKBgQDPGK+7s4ZC1HFvYbjF0v6XTagrrKGcMa57
nnbD9tszpq0NmromZZlKGRVIUhzs6x7lk29h+kt51dZog1u4jDBlemHzJ9SS9Z5A
o8vwZuI/fwlN3C8WjguTmo1wFDucOZIl9ULw5tkE+2TDUyDE6XQQv/UsfyvQqk+/
+0TdOmpVDwKBgQDLnwRPyWYcLZoNtuyCUmTLCEYADRjYhn9lvYOGoAWqunF9ZMDk
aAG+qXVzUHIkvXqtHRQUUFnijtSCJ3bGg4N+y46/UGSOtGKj5znbDgEonRkIVjfd
ceIwetqcgd9E6kk5o4goa9M6HD8dsRDqompp0Orcoe6t/Kz8BwTnCpCMKQKBgQCV
MiW4RfddwgsOwQoKip0bh7i17iJnkmsvZ9QMDZWRumxFtsiQzPUIKtXoSi/IhwK1
RegiX91sIp/an3e+llBvayGRuYotbYHa86YCxTwNnomnbA8IYsD4T4nByvG+9MLT
UcQuJUEHk8zd4s9izQTu5DvPGLcKFwhpOK496s2cBQKBgBnejbAgRWsDJx9ZIycr
E1jS31iRwYqkefpyRf4vRm0xdF3FajXcG4XNgKm9pn4GI/tlj6UxRl6zRJDebi1s
kU5F6i4ei3THk3p6DvVClO8j0H59NnNh5VIwvCpC2gDeWjeiciEUJwks+5ICecBa
tZIZ4Rfr2U7fGj+X3OUJtuDY
-----END PRIVATE KEY-----
"""
client_email = "ap-storage@streamlit-logger-466301.iam.gserviceaccount.com"
client_id = "117726017582086885213"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ap-storage%40streamlit-logger-466301.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
